variables:
  RAILS_ENV: test

before_script:
  - cp .env.example .env
  - bundle install --path=/home/gitlab-runner/builds/shared/${CI_PROJECT_NAME}/gems
  - nvm use v11.4.0
  - yarn install

test:
  script:
    - bundle exec rake

production:
  stage: deploy
  only:
    - ci_nvm
  script:
    - bundle exec cap production_1 deploy
    - bundle exec cap production_2 deploy

staging:
  stage: deploy
  only:
    - ci_nvm
  script:
    - bundle exec cap staging deploy
