Documentation:
  Enabled: false

LineLength:
  Enabled: false

CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Rails:
  Enabled: true

Bundler/OrderedGems:
  Enabled: false

BlockLength:
  Exclude:
    - 'spec/**/*.rb'
    - 'config/routes.rb'

Style/ExpandPathArguments:
  Exclude:
    - 'Rakefile'
    - 'spec/rails_helper.rb'
    - 'config/environment.rb'
    - 'config/application.rb'

AllCops:
  TargetRubyVersion: 2.4
  Exclude:
    - node_modules/**/*
    - bin/**/*
    - db/**/*
    - vendor/**/*
    - config/boot.rb
    - config.ru
    - config/application.rb
  CacheRootDirectory: tmp/
