language: ruby
cache: bundler
rvm:
  - 2.4.1

env:
  - DB_USERNAME=postgres DB_DATABASE=timetable_ci DB_HOST=localhost DB_PASSWORD=''

sudo: required
addons:
  postgresql: "9.6"
  chrome: stable

before_script:
  - yarn install
  - bundle exec rake db:create
  - cp .env.example .env
